method: giraffe
data:
  dataset_name: images
  path: /workspace/media/dataset1/jaehoon/carla/*.png
  classes: []
  img_size: 256
  fid_file: /workspace/media/dataset1/jaehoon/fid_files/carla_256.npz
  random_crop: False
  celebA_center_crop: False
  use_tanh_range: False
model:
  z_dim: 256
  z_dim_bg: 128
  decoder: simple
  #############################
  discriminator: dc                      #patchD or dc(plainD)
  patch_discriminator: patch               #patch or not
  #############################
  generator: simple
  background_generator: simple
  bounding_box_generator: simple
  neural_renderer: simple
  decoder_kwargs: {}
  discriminator_kwargs: {}
  patch_discriminator_kwargs: 
    netPatchD_scale_capacity: 4.0
    netPatchD_max_nc: 384     # 256 + 128
    patch_size: 16
    max_num_tiles: 8
    use_antialias: True

    spatial_code_ch: 8
    global_code_ch: 2048
    lambda_R1: 10.0
    lambda_patch_R1: 1.0
    lambda_L1: 1.0
    lambda_GAN: 1.0
    lambda_PatchGAN: 1.0
    patch_min_scale: 0.125
    patch_max_scale: 0.25
    patch_num_crops: 8
    patch_use_aggregation: True

  generator_kwargs: {}
  bounding_box_generator_kwargs: {}     # 
  neural_renderer_kwargs: {}
  background_generator_kwargs:
    hidden_size: 64
    n_blocks: 4
    downscale_p_by: 12
    skips: []
training:
  out_dir: out/reconcamgan_256_withswapgan_p
  batch_size: 16
  print_every: 10
  checkpoint_every: 10000
  visualize_every: 500
  validate_every: 10000
  backup_every: 1000000
  learning_rate: 0.0001  # 5e-5
  learning_rate_d: 0.00002  # 1e-5
  model_selection_metric: fid_score
  model_selection_mode: minimize
  n_workers: 8
  logfile: train.log
  overwrite_visualization: False
  multi_gpu: false
  optimizer: RMSprop
  optimizer_kwargs: {}
  n_eval_images: 10000
  range_u: [0.0, 1.0]
  range_v: [0.0, 0.5]
  recon_weight:  100.
  cam_loss_weight: 1
test:
  model_file: model_best.pt
  n_images: 20000
  take_generator_average: True
rendering:
  render_dir: rendering
  render_program: ['object_translation_vertical', 'object_translation_horizontal', 'object_rotation', 'interpolate_app', 'interpolate_shape', 'interpolate_app_bg']
